ronin-co/blade

README.md
This change ensures the correct size for all headings in the `README.md` file.
=> Correctly format readme headings

examples/basic/tsconfig.json
This change adds a missing `tsconfig.json` file to the basic example.
=> Add TS config to basic example

README.md
This change adds docs for the exported `use` React hook to the readme.
=> Document `use` hook

README.md
This change adds docs for the exported `useCookie` React hook to the readme.
=> Document `useCookie` hook

README.md, private/client/components/history.client.tsx, private/client/hooks.ts, private/client/utils/fetch-page.ts, public/client/components/link.client.tsx, public/client/hooks.ts, public/universal/hooks.ts
This change ensures that links are prefetched on hover (desktop) and touch start (mobile), which improved the performance of page transitions further.
=> Prefetch links on hover

private/shell/loaders.ts
Due to a limitation in Bun, we have to explicitly provide certain React imports during development. This change ensures that the runtime helpers for [JSX Fragments](https://react.dev/reference/react/Fragment) are imported correctly.
=> Ensure correct JSX Fragments

bun.lock, package.json, private/server/types/index.ts, public/universal/types.ts
This change further improves the changes landed in https://github.com/ronin-co/blade/pull/68 by exporting additional types for "pre" data hooks.
Data hooks will be announced shortly.
=> Expose types for pre-query data hooks

bun.lock, package.json
Previously, certain data hooks were automatically skipped if queries were ran within data hooks. We no longer need that.
The changes were originally added in https://github.com/ronin-co/client/pull/121.
=> Avoid auto-skipping data hooks

private/shell/utils.ts
This change updates how we handle using the Tailwind CSS CLI to bundle our CSS such that we actually handle errors returned by the CLI, rather than silently swallowing them.
=> Improve Tailwind CSS build error handling

private/shell/index.ts
This change adds support for a `--port` flag, which is required by `vercel dev`.
=> Added `--port` flag

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change introduces the feature added in https://github.com/ronin-co/blade/pull/89 to all Blade examples.
=> Added `--port` support for examples

README.md
This change ensures that the readme clearly states how to deploy Blade.
=> Clarify zero config deployments

examples/advanced/bun.lock, examples/advanced/package.json, examples/advanced/triggers/post.ts, examples/basic/bun.lock, examples/basic/package.json
This change fixes the `advanced` example from a recent change where `hooks` were renamed to `triggers`, as well as updating the name of the exports to use the `resolving` prefix.
Along with this, both examples have been upgraded to version `0.4.3`
=> Rename `advanced` example's `hooks` to `triggers`

biome.json
Since our release bot currently does not yet resume the format of `package.json`, we cannot let Biome format it.
=> Exclude JSON in Biome

public/client/components.tsx
This change improves the `Link` component and ensures that props passed to it are correctly considered.
See the code comment in the PR diff for additional details.
=> Correctly consider props for `Link` component

private/shell/utils/index.ts
This change ensures that Blade only prints these logs if `--debug` is passed as a flag:
The change also removes the temporary `--queries` flag in favor of `--debug`.
=> Correctly handle Bun debug logs

README.md, private/server/types/global.d.ts, private/server/worker/index.ts, private/shell/constants.ts, private/shell/utils/index.ts
This change introduces support for adding a `router.ts` file at the root of the project, which can export a [Hono](https://hono.dev) instance, allowing for capturing arbitrary URL paths:
```typescript
import { Hono } from "hono";
const app = new Hono()
.post('/some-path', (c) => c.text('Testing'));
export default app;
```
=> Add support for custom Hono instance

README.md
Now that support for Cloudflare has landed in https://github.com/ronin-co/blade/pull/112, we need to update our docs accordingly.
=> Update docs for Cloudflare Workers

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change upgrades the version of `@ronin/blade` used by both the `advanced` & `basic` example to version `0.7.13`.
=> Ensure latest package version for examples

examples/advanced/pages/about.tsx, private/shell/utils/index.ts
This change fixes the `advanced` example's `/posts` page which is currently throwing an error when deployed to Cloudflare due to a `BLADE_APP_TOKEN` missing.
=> Fix Cloudflare deployments default app token

bun.lock, package.json, public/server/components.tsx
Since RONIN no longer offers a `displayAs` field attribute that lets you display JSON fields as rich text, we can also remove the respective component from this package.
Originally, the change was landed in https://github.com/ronin-co/react-client/pull/6.
=> Removed `RichText` component

private/shell/index.ts
CSS and environment file changes now trigger hot reload in Blade.
=> Hotreload when `.css` or `.env` files change

private/shell/index.ts
This change was missing from https://github.com/ronin-co/blade/pull/136 and prevents Blade from crashing if the files mentioned in the PR don't exist.
=> Only watch files if they exist

private/server/components/root.tsx
This change ensures that the `description` field provided to `useMetadata` is correctly recognized.
=> Add support for meta description

bun.lock, package.json
We now correctly pass the models to the codegen package.
This change was originally landed as part of ronin-co/cli#104.
=> Correctly generate TS types

docs/pages/api-routes.mdx, docs/pages/client.mdx, docs/pages/layout.tsx, docs/pages/pages.mdx, docs/pages/types.mdx
This change adds the following pages to the docs site:
- "API Routes"
- "Pages"
- "Client"
- "Types"
The arrangement of the pages, their names and also contents will be refined further shortly.
=> Added remaining docs pages

private/shell/index.ts
This change updates the primary shell entrypoint's hot-reloading logic so it no longer throws an error if `pages/index.tsx` is not provided. The primary use case of which is if you are using a `pages/index.mdx` instead. Which this change also accounts for.
=> Fix MDX hot-reloading

docs/bun.lock, docs/package.json
This change upgrades the version of `@ronin/blade` used by the docs to version `0.8.4`.
=> Ensure latest package version for docs

docs/styles.css
This change adds a style fix for the documentation to correctly set the text color of headers, and `<strong>` elements, to be white.
=> Fix docs header text color

docs/pages/deploying.mdx, docs/pages/layout.tsx
This change adds a new documentation page named "Deploying", which talks about how to deploy Blade to prod.
=> Added initial docs for deploying

docs/components/code.tsx, docs/styles.css
This change reduces the margin between paragraphs in  our documentation.
Additionally this also fixes a bug with code snippets where the text was overflowing off the screen. Instead the text will now wrap to the next line.
=> Reduce documentation paragraph vertical margin

docs/pages/hooks.mdx
After https://github.com/ronin-co/blade/pull/175 has landed, we can now simplify the "Hooks" documentation page.
=> Simplify hooks documentation

docs/components/heading.client.tsx, docs/pages/layout.tsx
Previously, only the h1 element was replaced with our custom heading. Now, all heading elements have been updated to include support for an anchor tag, allowing users to copy the URL to the clipboard.
=> All headings in docs now have anchor tags

biome.json, docs/pages/hooks.mdx, package.json, public/server/hooks.ts, public/universal/hooks.ts
This change ensures that the `useCookie` hook already available on the server also starts working client-side.
=> Make `useCookie` work on the client

private/universal/hooks.ts
This change ensures that hashes are correctly retained in URLs and not stripped from them.
=> Retain hashes in URLs

docs/bun.lock, docs/components/menu.client.tsx, docs/components/navbar.tsx, docs/components/sidebar.tsx, docs/package.json
This PR bumps `ronin/blade` to `0.8.8`.
=> Bump blade in the docs for linked headings

private/server/utils/serializer.ts
This change ensures that components receiving functions via arguments render on the server without errors.
If a component is desired to be interactive, it can be marked as a client component. Not doing so should work fine too, and not cause an error.
=> Prevent server errors for event handlers

docs/components/heading.client.tsx
This PR enables support for headings that include React elements, such as inline code snippets.
=> Docs now support headings with code snippets

docs/components/copy.client.tsx, docs/components/footer.tsx, docs/components/theme-toggle.client.tsx, docs/components/ui/button.tsx, docs/pages/layout.tsx, public/universal/hooks.ts
This change fixes a small bug with the `useCookie` hook where if no `options.path` property was provided on the client then no `path` would be set in the cookie, which does not match the server-logic.
Additionally this also applies a few smaller fixes for our documentation site, namely the following:
- `CopyToClipboard` trigger button now enables `asChild`
- Prop drill theme cookie initial value from layout
- `Button` component now wrapped in `forwardRef`
=> Add default path to client-side `useCookie` setter

docs/pages/layout.tsx
This change updates the `useMetadata` hook in the documentation sites root layout to add a `description` property to improve SEO.
=> Add description to documentation site

docs/components/theme-toggle.client.tsx, docs/pages/layout.tsx, docs/styles.css
This change updates our theme selection logic to default to the system preferred color scheme when no `theme` cookie exists. Otherwise we will add either a `light` or `dark` class to the top-level `html` element.
=> Ensure reliable theme selection

docs/components/navbar.tsx, private/client/index.ts, private/client/types/global.d.ts, private/client/utils/fetch-page.ts, private/client/utils/wrap-client.ts, private/server/components/root.tsx, private/server/worker/index.ts, private/server/worker/tree.ts, private/shell/constants.ts, private/shell/index.ts, private/shell/listener.ts, private/shell/loaders.ts, private/shell/types.ts, private/shell/utils/index.ts, private/shell/utils/providers.ts, private/universal/types/global.d.ts, private/universal/utils/constants.ts, private/universal/utils/paths.ts, tsup.config.ts
Instead of performing a server and a client build, this change ensures that we only perform one build, which allows for speeding up HMR (and builds in general) even further.
=> Use a single build

docs/pages/deploying.mdx
As suggested in [this post](https://x.com/longtilwrong/status/1935767472285860126), I'm adding a Dockerfile example to the "Deploying" page in the docs!
A `fly.toml` example will follow shortly as well — the Dockerfile already makes it possible to deploy Blade to Fly.io! 🚀
=> Add Dockerfile example to docs

docs/components/heading.client.tsx, docs/components/navbar.tsx, docs/pages/layout.tsx
Align table of contents, the first heading and the sidebar.
=> Align first heading with sidebar

private/shell/index.ts
Now that https://github.com/ronin-co/blade/pull/187 and https://github.com/ronin-co/blade/pull/222 have landed, we can make `blade serve` work with esbuild builds.
=> Correctly serve app in containers

docs/bun.lock, docs/package.json, examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change adds version [0.9.0](https://github.com/ronin-co/blade/releases/tag/0.9.0) of Blade to all examples and the docs.
=> Use latest version of package for examples

private/shell/index.ts
This change adjusts the development server to use polling for watching files, in order to make HMR work on WSL.
=> Correctly watch files on WSL (Windows)

private/shell/constants.ts, private/shell/index.ts
This PR resolves issues with the `init` command by correctly defining the path to example projects. It removes automatic git initialization and switches from bun primitives to Node for data copying.
=> Fix `init` command

packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/index.ts
In https://github.com/ronin-co/blade/pull/222, a regression was introduced that prevented pages with multiple client components from getting serialized correctly.
The change right here resolves that issue.
=> Correctly serialize elements

.github/workflows/post-release.yml
This change adds a basic GitHub actions workflow to run every time a new release is created and post a message to `#releases` channel in [our Discord](https://discord.gg/ronin).
=> Add post-release workflow

.github/workflows/post-release.yml
This change refines the styles for Discord release messages by setting the accent color to `#5197ed`.
=> Refine Discord release message styles

biome.json, packages/blade/private/shell/index.ts, packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/index.ts, packages/blade/private/shell/utils/providers.ts
This change replaces Bun-specific APIs with Node.js APIs where possible, to reduce our dependence on Bun.
This contributes to https://github.com/ronin-co/blade/issues/205.
=> Rely on Node.js APIs where possible

docs/components/snippet.client.tsx, docs/pages/deploying.mdx, docs/pages/index.mdx, docs/pages/pages.mdx, packages/blade/README.md
This change replaces all occurrences of `bun blade init` with the new `bun create blade` since that is our new recommended standard for scaffolding a new Blade project.
This closes #213.
=> Replaced `bun blade init` with `bun create blade`

packages/blade/private/shell/loaders.ts
This change resolves an issue that was reported [on Discord](https://discord.com/channels/1099977902629589095/1099977903678173206/1388342152697741434) by ensuring that API Routes work as expected.
=> Ensure correct API Routes

docs/components/alert.tsx, docs/components/ui/alert.tsx, docs/pages/deploying.mdx
This change updates the documentation on deploying a Blade project to Cloudflare Workers.
Additionally this fixes a slight layout bug with the documentation `AlertCard` component.
=> Improve Cloudflare deployment documentation

packages/blade/private/client/hooks.ts, packages/blade/private/client/index.ts, packages/blade/private/client/types/global.d.ts, packages/blade/private/client/utils/page.ts
This change ensures that the stream of server pushes is closed when a new client bundle mounts, since the stream relies on a particular version of React, which might get replaced with the new bundles.
Once the new bundles are mounted, they will automatically open a new stream themselves.
=> Improved reliability of server pushes

packages/blade/private/client/components/history.tsx, packages/blade/private/client/types/util.ts, packages/blade/private/server/context.ts, packages/blade/private/server/worker/index.ts, packages/blade/private/universal/context.ts, packages/blade/private/universal/types/util.ts
Now that Blade keeps a connection open to the server in order to flush UI updates, we can also handle our regular revalidation interval like that, by having the server push updates instead of having the clients poll them.
Since the SSE connection is automatically re-established after the device comes back online and the server already issues an immediate update for every newly established session, we also no longer need the client logic for revalidating when the device comes back online.
This will come in especially handy once we flush UI updates based on changes to data, since those stem from the server as well, which means they can all use a single pipeline.
=> Revalidate UI from the server

packages/blade/private/server/components/root.tsx
This change ensures that the Open Graph URL in the `<head>` is populated.
=> Populate Open Graph URL

packages/blade/private/client/hooks.ts, packages/blade/private/client/utils/page.ts, packages/blade/private/server/worker/tree.ts, packages/blade/private/universal/types/util.ts, packages/blade/public/client/hooks.ts
This change ensures that [this bug](https://discord.com/channels/1099977902629589095/1392158060599967744/1392619471692370054) reported on Discord no longer occurs, meaning that hovering links will no longer cause a page transition — only clicking them will:
https://github.com/user-attachments/assets/acb9059a-da58-4cd9-a96e-2e5be0bc9c8d
=> Prevent incorrect revalidation

bun.lock, package.json, packages/blade-compiler/package.json, packages/blade-syntax/package.json, packages/blade-syntax/src/helpers/expressions.ts, packages/blade-syntax/src/helpers/functions.ts, packages/blade-syntax/src/queries/index.ts, packages/blade-syntax/src/queries/statements.ts, packages/blade-syntax/src/queries/types.ts, packages/blade-syntax/src/schema/model.ts, packages/blade-syntax/src/schema/primitives.ts, packages/blade-syntax/tests/queries/index.test.ts, packages/blade-syntax/tests/queries/statements.test.ts, packages/blade-syntax/tests/schema/model.test.ts
This change ensures that the `blade-syntax` package correctly imports the `blade-compiler` package.
=> Import local packages

.github/workflows/publish-experimental.yml
This change re-adds support for publishing experimental packages for us to use and test with, but this time using [pkg.pr.new](https://pkg.pr.new) for every PR.
=> Add experimental package releases

packages/blade/private/server/worker/triggers.ts
This change fixes a slight regression as part of #324 where I accidentally removed binding the server context `flushSession`  to the trigger options.
=> Ensure `flushSession` is exposed to trigger options

packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts
This change ensures that the server doesn't try to push updates to clients that are no longer connected.
=> End revalidation when client disconnects

docs/pages/models/index.mdx, docs/pages/queries/functions.mdx, packages/blade-better-auth/README.md, packages/blade-cli/src/commands/pull.ts, packages/blade-cli/tests/utils/pull.test.ts, packages/blade-client/package.json, packages/blade-client/src/schema/index.ts, packages/blade-syntax/src/schema/primitives.ts, packages/blade/private/shell/utils/build.ts, packages/blade/public/universal/schema.ts
This change replaces all occurrences of `ronin/schema` with `blade/schema`, in order to simplify the syntax used when defining models in Blade.
=> Ensure correct schema imports

packages/blade-client/types/index.d.ts, packages/blade/tsup.config.ts
Prior to this change, the exported TypeScript files of the main package were importing packages that are only available within the workspace, which caused the main package's exports to be invalid.
=> Bundle types in main package

packages/blade/private/server/utils/polyfills.ts, packages/blade/private/server/worker/index.ts
This change ensures that responses are automatically compressed if Blade is run inside a container.
=> Enable response compression in containers

packages/blade-hono/tests/integration.test.ts, packages/blade/private/shell/index.ts, packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/build.ts, packages/blade/private/shell/utils/index.ts, packages/blade/public/universal/utils.ts
This change adds a new `esbuild` loader for Tailwind CSS, in order to tightly integrate Tailwind CSS into the build.
=> Use loader for Tailwind CSS styles

packages/blade/private/client/components/history.tsx
This change ensures that revalidation is always triggered from the server-side (instead of from the server-side and from the client-side), to avoid race conditions.
=> Avoid unnecessary revalidation

packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts
This change ensures that the UI doesn't flicker while the server is streaming changes to the client.
=> Prevent revalidation flickers during streaming

packages/blade-cli/src/commands/login.ts
This PR fixes the base URL provided when using the `login` sub-command by correctly pointing to the new RONIN Studio API endpoint.
=> Fix `login` command base URL

packages/blade/private/shell/loaders.ts
This changes prevents Blade from incorrectly recognizing type exports as runtime code exports, which is a bug that is currently blocking the deployments of our docs.
=> Correctly parse client components

packages/blade/private/client/utils/page.ts, packages/blade/private/server/components/root.tsx, packages/blade/private/shell/utils/build.ts, packages/blade/private/universal/types/util.ts, packages/blade/private/universal/utils/paths.ts
This change ensures that the client preloads the bundle chunk that is shared between client and server, instead of waiting for the main client entry point to download it (the latter is slower).
=> Preload universal bundle code

packages/blade/package.json
This change ensures that our exports are compatible with the [Node.js spec](https://nodejs.org/api/packages.html#package-entry-points) for `exports`.
Our previous configuration worked with many tools, but seemingly isn't spec compliant, so it caused [resolve-from](https://www.npmjs.com/package/resolve-from) (which uses Node.js internals for resolving) to not find the exports.
=> Improved export compatibility

packages/blade-cli/src/utils/format.ts
This PR fixes a small bug since #396 where the `getPath` method from `@dprint/typescript` relies on `__dirname`, which is not defined in `blade`. As such I have added logic to polyfill the `__dirname` global.
=> Fix WASM module path resolution

bun.lock, package.json
This PR upgrades our workspace tool `turbo` to version `2.5.6`.
=> Upgrade workspace tooling

bun.lock, packages/blade-client/package.json, packages/blade-client/src/queries.ts, packages/blade-client/src/types/utils.ts, packages/blade-client/tsconfig.json, packages/blade/private/server/types/index.ts, packages/blade/private/server/types/server-list.d.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/build.ts
This change enables Blade to compile Blade queries to SQL directly in its codebase, instead of having a production service take care of that, which will make debugging easier as well.
=> Let Blade compile queries locally

bun.lock, packages/blade-cli/package.json, packages/blade-cli/src/commands/apply.ts, packages/blade-cli/src/commands/diff.ts, packages/blade-cli/src/index.ts, packages/blade-cli/src/utils/model.ts, packages/blade-client/package.json, packages/blade-client/src/bin/index.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/shell/index.ts
This change adds a new experimental flag (currently only meant to be used by the RONIN team) for enabling the new database engine (introduced in https://github.com/ronin-co/blade/pull/413) within the `blade diff` and `blade apply` commands.
=> Prepare migration CLI for new engine

bun.lock, packages/blade-better-auth/package.json, packages/blade-better-auth/tests/fixtures/utils.ts, packages/blade-cli/package.json, packages/blade-cli/src/utils/model.ts, packages/blade-cli/tests/fixtures/utils.ts, packages/blade-compiler/package.json, packages/blade-compiler/tests/fixtures/utils.ts
This change adds the new database engine for all of our tests and removes the old one entirely.
=> Use new engine for tests

packages/blade/private/shell/utils/providers.ts
This change updates the default `wrangler.jsonc` config file generated when deploying to Cloudflare Workers to enable the `nodejs_compat` compatibility flag.
=> Enable `nodejs_compat` flag in default Wrangler config

docs/pages/api-routes.mdx, docs/pages/client.mdx, docs/pages/hooks.mdx, docs/pages/models/index.mdx, docs/pages/models/triggers.mdx, docs/pages/queries/crud.mdx, docs/pages/queries/index.mdx, docs/pages/queries/instructions.mdx
This change makes a number of small tweaks to the Blade documentation to both:
- Replace all instances of using the `ronin` CLI in favour of the `blade` CLI since they are now interoperable
- Fixed a number of broken links
=> Replaced `ronin` CLI documentation with `blade` CLI

docs/pages/layout.tsx, packages/blade/private/server/worker/tree.ts
This change ensures that, if the same query is used across multiple leaves of a rendering tree (layouts and pages), it will be deduped and only executed once.
=> Correctly dedupe queries

packages/blade-client/src/queries.ts, packages/blade-client/src/utils/triggers.ts
Instead of invoking all available types of triggers in a single function, this change splits the invocation logic for different types of triggers into two different functions:
- One function for [synchronous triggers](https://blade.im/models/triggers#synchronous-triggers)
- One function for [asynchronous triggers](https://blade.im/models/triggers#asynchronous-triggers)
This will make subsequent changes easier.
The tests are unchanged and are passing as-is, so the behavior didn't change — only the structure of the code.
=> Refactor trigger invocation logic

packages/blade/private/server/worker/tree.ts
If the server-side performs a redirect, subsequent UI flushes (be it revalidation or manually triggered ones) have to consider the new URL instead of the one for which the stream session was originally created.
=> Ensure up-to-date session URL

packages/blade/private/server/worker/tree.ts
This change was missing from https://github.com/ronin-co/blade/pull/437 and prevents errors during UI flushing.
=> Prevent error while flushing UI

packages/blade/private/shell/constants.ts, packages/blade/private/shell/utils/build.ts
This change adds a configuration property named `external`, which can be used to instruct Blade not to bundle certain dependencies that, for example, aren't compatible with serverless environments.
The configuration property can be defined in `package.json` like this:
```json
{
"blade": {
"external": ["a-package"]
}
}
```
Documentation for this property will follow separately. First we must prove whether it even deserves to exist.
=> Add support for external dependencies

docs/pages/hooks.mdx, docs/pages/queries/instructions.mdx, packages/blade/public/client/hooks.ts, packages/blade/public/server/hooks.ts
So far, Blade has been using `previousPage` and `nextPage` as pagination cursors, while the underlying query client has been using `moreBefore` and `moreAfter` instead.
The change right here ensures that only `moreBefore` and `moreAfter` remain, to avoid multiple different properties that serve the same purpose.
=> Ensure clarity for pagination cursors

bun.lock, packages/blade-client/src/queries.ts, packages/blade-client/src/types/utils.ts, packages/blade-compiler/README.md, packages/blade-compiler/src/index.ts, packages/blade-compiler/src/instructions/to.ts, packages/blade-compiler/src/utils/index.ts, packages/blade-compiler/tests/options.test.ts, packages/blade/private/server/utils/data.ts
This change ensures that Blade provides 20 records per page by default, which is already documented.
We will keep tweaking this limit. The client/compiler does not impose a default limit itself.
=> Enable pagination by default

docs/pages/hooks.mdx, packages/blade/public/server/hooks.ts
This hook has been destined to be removed for a very long time, and I decided that now is a good time to do so.
The last valid use case for it was setting cookies as a result of mutations, which is a responsibility that triggers will take over for the time being.
=> Removed `useMutationResult` hook

docs/pages/pages.mdx
This change updates our "Pages" documentation to add a section explaining how to host static assets or files in a Blade project.
=> Add static assets documentation

packages/blade-codegen/src/declarations.ts, packages/blade-codegen/src/generators/syntax.ts, packages/blade-codegen/tests/__snapshots__/index.test.ts.snap, packages/blade-codegen/tests/generators/__snapshots__/namespaces.test.ts.snap, packages/blade-codegen/tests/generators/__snapshots__/syntax.test.ts.snap
This change upgrades the code generation to improve the types used for queries such `.with(...)` queries. Now the properties or fields recommended are based on the singular schema. But we also retain the existing default combined instructions type, which allows for loose typing in order to support [advanced assertions](https://blade.im/queries/instructions#advanced-assertions).
In future I will improve this even more by making it so both:
- The combined instructions fallback is not needed & instead advanced assertions are supported by default
- Similarly nested link field properties are supported so you could have the following query be fully typed: `use.post.with({ author: { slug: '...' } })`
=> Improve `with` query typed fields

bun.lock, packages/blade/private/server/types/index.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/server/worker/tree.ts
Since https://github.com/ronin-co/blade/pull/493 has landed (check out the pull request for more details), the `flushSession` option that is currently being provided to triggers is no longer needed.
=> Removed `flushSession` option from triggers

packages/blade/private/server/utils/index.ts, packages/blade/private/server/worker/tree.ts
When flushing many UI updates, older updates might take longer to process than newer ones, which would cause the UI to temporarily get reverted back to an old state.
The change right here ensures that we track the time of the last update, so that only newer updates are ever applied.
This is better than queueing the flushes, since it ensures maximum speed and "the fastest wins", while still ensuring UI consistency. Queueing the flushes would be slow.
=> Prevent race condition during UI flushing

bun.lock, packages/blade-better-auth/package.json, packages/blade-cli/package.json, packages/blade-cli/tsdown.config.ts, packages/blade-client/package.json, packages/blade-client/src/queries.ts, packages/blade-client/src/types/utils.ts, packages/blade-client/tests/integration/factory.test.ts, packages/blade-client/tsdown.config.ts, packages/blade-compiler/package.json, packages/blade/package.json, packages/blade/private/shell/utils/build.ts, packages/blade/tsdown.config.ts
This change temporarily ensures that only one connection is maintained for all writes per Blade instance.
However, this behavior is only enabled if the `undici` package is installed.
=> Optionally limit writes to 1 DB connection

bun.lock, packages/blade-client/src/queries.ts, packages/blade/private/server/worker/tree.ts
This change ensures that HTTP/2 is retained for writes, but multiplex streams are disabled to ensure order for writes.
=> Support HTTP/2 for writes

bun.lock, packages/blade-better-auth/package.json, packages/blade-cli/package.json, packages/blade-client/package.json, packages/blade-compiler/package.json
Bumps `hive` to version `2.1.4`, landing various WebSocket and http layer improvements.
=> Bump `hive` to `2.1.4`

bun.lock, packages/blade-better-auth/package.json, packages/blade-cli/package.json, packages/blade-client/package.json, packages/blade-codegen/package.json, packages/blade-compiler/package.json, packages/blade-syntax/package.json, packages/blade/package.json, packages/blade/private/shell/utils/build.ts, packages/create-blade/package.json
This PR upgrades the version of `rolldown` used by the `blade` package to `1.0.0-beta.41`.
As part of this change includes resetting the `bun.lock` file which bumps the version of `rolldown-plugin-dts` which should fix the on-going CI failures.
=> Upgrade to `rolldown` beta version 41

packages/blade-client/src/queries.ts, packages/blade-client/src/types/utils.ts, packages/blade-client/tests/integration/factory.test.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/server/worker/tree.ts
This change applies a few more improvements that were missing from https://github.com/ronin-co/blade/pull/523.
As a result, the database caller (the function calling the database) now has access to the identifier of the current stream, which allows it to open multiple parallel streams for writes. We're not yet leveraging those, but will eventually.
=> Improved stream selection logic

packages/blade/private/server/utils/index.ts, packages/blade/private/server/worker/tree.ts
This change resolves a bug where the rendering of a page incorrectly gets blocked on write queries.
=> Avoid blocking page render on write streams

packages/blade/private/server/worker/tree.ts
Previously, streamed UIs would temporarily get reverted to old query results, which this change resolves.
=> Prevent flicker during UI streaming

packages/blade/public/client/components.tsx
This PR updates the `Link` client component to always wrap the child component(s) in an anchor element. Currently you must do this by hand. If you did not, Blade would throw an error / show a type error.
As such with this change we can now close #366.
=> Ensure the `Link` always wraps children in an anchor element

packages/blade/private/client/components/history.tsx, packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts
At the moment, the browser history does not get managed correctly, due to a bug that was introduced recently.
The change right here ensures that browser history entries are added correctly.
=> Ensure correct browser history order

packages/blade/private/server/worker/tree.ts, packages/blade/tsdown.config.ts
https://github.com/ronin-co/blade/pull/539 broke Cloudflare Workers. The change right here makes them work again.
=> Ensure React 19.2.0 support on CF Workers

docs/pages/deploying.mdx, packages/blade/private/shell/constants.ts, packages/blade/private/shell/listener.ts, packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/build.ts, packages/blade/private/shell/utils/providers.ts, packages/blade/private/universal/utils/constants.ts, packages/blade/private/universal/utils/paths.ts
This change closes #538 by refining the structure of Blade's build output (see docs in the diff).
=> Correctly scope `public` directory

packages/blade-cli/src/commands/apply.ts, packages/blade-cli/src/commands/types.ts, packages/blade-cli/src/index.ts, packages/blade-cli/tests/index.test.ts, packages/blade-codegen/src/constants/schema.ts, packages/blade-codegen/src/generators/comment.ts, packages/blade-codegen/src/generators/model.ts, packages/blade-codegen/src/generators/namespaces.ts, packages/blade-codegen/src/generators/syntax.ts, packages/blade-codegen/src/index.ts, packages/blade-codegen/src/types/model.ts, packages/blade-codegen/src/types/query.ts, packages/blade-codegen/src/utils/types.ts, packages/blade-codegen/src/zod.ts, packages/blade-codegen/tests/generators/__snapshots__/model.test.ts.snap, packages/blade-codegen/tests/generators/comment.test.ts, packages/blade-codegen/tests/generators/model.test.ts, packages/blade-codegen/tests/generators/namespaces.test.ts, packages/blade-codegen/tests/generators/syntax.test.ts, packages/blade-compiler/src/index.ts, packages/blade/private/shell/index.ts
This change ensures that `blade types` works for local models, even if no database exists yet.
=> Make `blade types` work locally
