ronin-co/blade

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json, examples/basic/pages/index.tsx
Blade does not yet support version 4 of Tailwind, but support will be added shortly.
=> Ensure correct Tailwind version

README.md
This change fixes a few typos in the readme.
=> Improved docs further

README.md
This change documents how automatic revalidation is handled in Blade.
=> Add revalidation docs

README.md
This change replaces `npx` with `bunx` in the readme.
=> Use `bunx` instead of `npx`

README.md
This change adds additional documentation for the React hooks that Blade exposes.
=> Add additional docs for hooks

private/shell/index.ts
This change ensures that Blade correctly watches files during development.
=> Correctly watch files

bun.lock, package.json
This change bumps the versions of all dependencies that have an available security patch.
=> Bump patchable dependencies

README.md, private/server/types/global.d.ts, private/server/types/index.ts, private/server/worker/pages.ts, private/server/worker/tree.ts, private/shell/constants.ts, private/shell/utils/index.ts
This change ensures that default error pages are correctly included in Blade's package bundle.
=> Correctly bundle default error pages

private/client/components/history.tsx, private/client/context.ts, private/client/hooks.ts, private/client/index.ts, private/client/utils/fetch-page.ts, private/server/components/root.tsx, private/server/hooks.ts, private/server/types/index.ts, private/server/utils/data.ts, private/server/utils/pagination.ts, private/server/utils/request-context.ts, private/server/worker/context.ts, private/server/worker/index.ts, private/server/worker/pages.ts, private/server/worker/tree.ts, private/server/worker/triggers.ts, private/shell/builder.ts, private/shell/index.ts, private/shell/listener.ts, private/shell/loaders.ts, private/shell/utils/index.ts, private/shell/utils/providers.ts, private/universal/context.ts, private/universal/hooks.ts, private/universal/types/util.ts, private/universal/utils/paths.ts, tests/fixtures/pages.ts, tests/unit.test.ts, tsconfig.json
Now that https://github.com/ronin-co/blade/pull/78 has landed, we can use our desired import syntax.
=> Improved import syntax

private/shell/builder.ts, private/shell/utils/index.ts, private/universal/types/global.d.ts, private/universal/types/util.ts
This change was missing from https://github.com/ronin-co/blade/pull/67 and further improves support for Vercel.
=> Ensure correct client bundles on Vercel

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change ensures that all examples use the latest version of Blade.
=> Use latest version of Blade for examples

examples/advanced/README.md, examples/basic/README.md
This change deploys all Blade examples to Vercel.
=> Deploy examples to Vercel

README.md
This change adds an improved project description in the `README.md` file.
=> Improved readme description

private/client/utils/fetch-page.ts, private/server/components/root.tsx
This change ensures that HMR (Hot Module Replacement) works reliably.
=> Ensure reliable HMR

bun.lock, package.json
This change ensures that Blade can make use of the latest RONIN client changes.
=> Ensure latest RONIN client version

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change ensures that the examples are using the latest Blade version.
=> Upgrade examples to latest Blade version

examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
Add `@types/react` and `@types/react-dom` to the example apps.
=> Add react types to example apps

README.md, examples/advanced/bun.lock, examples/advanced/package.json, examples/basic/bun.lock, examples/basic/package.json
This change upgrades the version of Blade on the examples to the latest version.
=> Ensure latest package version for examples

private/client/utils/wrap-client.ts
This change ensures that the `Image` component works correctly.
=> Ensure working `Image` component

bun.lock, package.json, private/server/types/global.d.ts, private/server/utils/request-context.ts
We no longer need this logic, since Blade is being fronted by CDNs that provide geo-location information.
=> Removed timezone mapping

private/server/worker/providers/cloudflare.ts, private/shell/builder.ts, private/shell/utils/providers.ts
This change ensures that Cloudflare deployments are working as expected.
=> Ensure correct Cloudflare deployments

private/shell/index.ts
Initialize git and add a `.gitignore` file.
=> Initialize git on `blade init`

docs/biome.json, docs/bun.lock, docs/components/code.tsx, docs/package.json
This change makes a few minor tweaks to the `docs/` app to make it ready for deployment.
=> Deploy documentation

docs/components/sidebar.tsx, docs/pages/layout.tsx
The sidebar now supports sections.
=> Add section support

docs/pages/components.mdx, docs/pages/index.mdx, docs/pages/layout.tsx, docs/pages/queries/index.mdx
This change ensures a cleaner "Introduction" page for the docs.
=> Improved docs introduction

docs/components/menu.client.tsx, docs/components/ui/sheet.tsx
Updated the font size of menu items and repositioned the close button above the hamburger menu in the docs.
=> Position docs navigation menu close button

docs/components/heading.client.tsx, docs/pages/layout.tsx
Added ids to heading elements so that we can scroll to the desired element.
=> Add ID to headings

docs/components/logo.tsx, docs/components/metallic.tsx, docs/styles.css
Updated styles for correct paragraph and logo display in light mode.
=> Adjust docs to support light mode

docs/bun.lock, docs/package.json
This change upgrades the version of `@ronin/blade` used by the docs to version `0.8.10`.
=> Ensure latest package version for docs

docs/pages/index.mdx
This change ensures that no duplicated docs are present on the "Introduction" page.
=> Removed duplicated docs

private/client/utils/parser.ts
This change simplifies the client-side JSX stream parser.
=> Simplify JSX parser

docs/components/code.tsx, docs/components/heading.client.tsx, docs/pages/layout.tsx, docs/styles.css
This change updates the heading styles for our documentation site to add the correct spacing and font sizing.
=> Fix documentation heading spacing

docs/pages/deploying.mdx
This change improves the example added in https://github.com/ronin-co/blade/pull/224 even further!
=> Improved Dockerfile example in the docs

bun.lock, package.json, private/client/components/history.tsx, private/client/hooks.ts, private/client/index.ts, private/client/utils/fetch-page.ts, private/shell/index.ts, private/shell/listener.ts, private/shell/utils/index.ts
This change re-enables HMR after we've merged our new build system in https://github.com/ronin-co/blade/pull/187 and https://github.com/ronin-co/blade/pull/222.
=> Ensure correct HMR

private/client/index.ts, private/client/types/global.d.ts, private/shell/index.ts, private/shell/loaders.ts, private/shell/utils/index.ts, tsup.config.ts
This change ensures that no unnecessary code is bundled into the client-side of Blade.
=> Correctly handle imports

docs/components/param-field.client.tsx, docs/components/param-field.tsx, docs/pages/components.mdx
Simple param field component for displaying props.
=> Added param field component

docs/bun.lock, docs/components/footer.tsx, docs/components/nav.tsx, docs/components/table-of-contents.client.tsx, docs/components/theme-toggle.client.tsx, docs/package.json, docs/pages/layout.tsx, packages/blade/examples/advanced/bun.lock, packages/blade/examples/advanced/components/add-post.client.tsx, packages/blade/examples/advanced/package.json, packages/blade/examples/advanced/pages/posts/[id].tsx, packages/blade/examples/advanced/pages/posts/index.tsx, packages/blade/examples/advanced/triggers/post.ts, packages/blade/examples/basic/bun.lock, packages/blade/examples/basic/package.json
This change adds the updated package name from https://github.com/ronin-co/blade/pull/258 to our examples and docs!
=> Use updated package name for examples

docs/bun.lock, docs/components/header.client.tsx, docs/package.json
Update Blade to the latest version in the documentation to improve hash handling on page changes and ensure correct highlighting of active table of contents items. See related changes in https://github.com/ronin-co/blade/pull/271 and https://github.com/ronin-co/blade/pull/277.
=> Correctly handle hashes on page change in docs

docs/bun.lock, docs/package.json, packages/create-blade/templates/advanced/bun.lock, packages/create-blade/templates/advanced/package.json, packages/create-blade/templates/basic/bun.lock, packages/create-blade/templates/basic/package.json
This change introduces the latest version of Blade to the docs and the templates.
=> Upgrade templates and docs to latest version

docs/bun.lock, docs/package.json, packages/create-blade/templates/advanced/bun.lock, packages/create-blade/templates/advanced/package.json, packages/create-blade/templates/basic/bun.lock, packages/create-blade/templates/basic/package.json
This change ensures that the docs and the templates all use the latest version of Blade!
=> Use latest version for docs and templates

packages/blade/private/server/context.ts, packages/blade/private/server/types/index.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/server/utils/files.ts, packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts, packages/blade/private/server/worker/triggers.ts, packages/blade/private/universal/types/util.ts, packages/blade/public/client/hooks.ts, packages/blade/public/universal/types.ts
This change ensures that local packages are imported correctly. More changes will follow.
=> Improved local package imports

packages/blade/private/shell/loaders.ts, packages/blade/private/shell/utils/build.ts, packages/blade/private/shell/utils/index.ts, packages/blade/public/universal/utils.ts
This change ensures that the virtual `build` method also exposes styles!
=> Provide styles via `build` method

packages/blade/README.md
One of the readme links was broken, which this PR fixes.
=> Ensure correct readme links

docs/bun.lock, docs/package.json, packages/create-blade/templates/advanced/bun.lock, packages/create-blade/templates/advanced/package.json, packages/create-blade/templates/basic/bun.lock, packages/create-blade/templates/basic/package.json
This changes adds all of the recent improvements to the docs and our templates!
=> Add latest package version to docs and templates

bun.lock, packages/blade/package.json, packages/blade/private/shell/utils/build.ts, packages/blade/public/universal/utils.ts
This change ensures that dependencies are correctly resolved when performing in-memory builds.
=> Correctly resolve dependencies of in-memory builds

bun.lock
This PR updates our workspace lock file, which has fallen out of sync.
=> Pin latest lock file dependencies

packages/blade/private/server/utils/constants.ts, packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts
This change makes use of Hono's built-in security header feature instead of inlining the headers ourselves.
=> Improved security headers

packages/blade-cli/src/commands/apply.ts, packages/blade-cli/src/commands/diff.ts, packages/blade-cli/src/utils/model.ts, packages/blade-client/src/queries.ts, packages/blade/private/shell/index.ts
This change ensures that the diffing behavior works with the new engine (only meant to be used by the RONIN team for now, until we open it up for everyone shortly).
=> Made diffing and applying work with new engine

docs/pages/models/index.mdx
This change adds documentation for the `blade types` command.
=> Document `blade types` command

docs/pages/queries/index.mdx
This change adds docs for how to chain functions when writing queries.
=> Document function chaining for queries

packages/blade/README.md
This change ensures that the readme is up-to-date!
=> Removed unnecessary readme details

docs/components/header.client.tsx, packages/blade-client/src/index.ts, packages/blade-client/src/types/utils.ts, packages/blade-client/src/utils/helpers.ts, packages/blade/private/server/context.ts, packages/blade/private/server/types/index.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/server/worker/index.ts, packages/blade/private/server/worker/tree.ts
This closes https://github.com/ronin-co/blade/issues/322. Check out the issue for more details!
As a result, we can now also close https://github.com/ronin-co/blade/pull/340, which is an earlier implementation of this feature.
=> Add `flush` option for async write queries

bun.lock, packages/blade-better-auth/package.json, packages/blade-cli/package.json, packages/blade-client/package.json, packages/blade-compiler/package.json
This change ensures that no authentication errors show up when providing a valid token.
=> Resolve authentication error

packages/blade/private/server/context.ts, packages/blade/private/server/utils/data.ts, packages/blade/private/server/worker/tree.ts
This change simplifies the UI streaming logic in preparation for speeding up UI streams.
=> Simplify UI streaming logic

docs/bun.lock, docs/package.json, packages/create-blade/templates/advanced/bun.lock, packages/create-blade/templates/advanced/package.json, packages/create-blade/templates/basic/bun.lock, packages/create-blade/templates/basic/package.json
This change adds the latest version of Blade to all templates and the docs!
=> Add latest version to templates and docs

packages/blade-client/src/triggers/errors.ts, packages/blade/public/server/errors.ts
This change exports a few additional helper errors.
=> Added query type errors
